### ISSUE TITLE
Would it be possible to have a `set_bit` operation on BitVector?

### ISSUE THREAD

**Issue by GSGerritsen** [ajalab/fid#21]
The particular use case in which I'm thinking about this is for quick parallel construction of a `BitVector`. Specifically, let's say we had 10 bitvecs and we wanted to `or` them all together to produce a single bitvec containing all the set 1s.

The way I'm currently doing that is like this:
```
for i in 0..len {
  let mut found = false;
  for bv in bitvecs {
      if bv.get(i) {
          found = true;
          break;
      }
  }
  new_bitvec.push(found)
}
```

But unfortunately this approach is fairly slow. Ideally I could construct the new bitvector in blocks in parallel, calling `set_bit` within those blocks. Would something like this be possible in this crate? To summarize I'm basically looking to construct a `BitVector` in parallel. Thanks in advance for any pointers / ideas.

**Comment by ajalab** [comment]
Unfortunately, I'd say the implementation of `set_bit(i, b)` (set the `i`-th bit in a `BitVector` with flag `b`) would not be performant. It would take _O(n)_ time in the worst case, and can't be parallelized.

This is due to data structures that `BitVector` maintains - especially [`lblocks`](https://github.com/ajalab/fid/blob/276c485edd2888d2cc8f466e34297cf198c839d3/src/bit_vector.rs#L56-L57). The array [contains the total number of `1`s up to each sub-block (_superblock_) index](https://github.com/ajalab/fid/blob/276c485edd2888d2cc8f466e34297cf198c839d3/src/bit_vector.rs#L127). So for example, if we update the first bit of a `BitArray` with `set_bit(0, true)`, we end up updating the whole `lblocks` array we've ever built.  This also means that we can't update `lblocks` in parallel.

**Comment by GSGerritsen** [comment]
Got it, thank you for the response. Would you have any recommendations when using `fid` for this `or` operation I mentioned above? No worries if not, just wanted to make sure I wasn't overlooking anything in the crate.

**Comment by ajalab** [comment]
Sorry for the late reply, but sadly, I have no ideas about more efficient solutions than you're doing now.

**Comment by GSGerritsen** [comment]
No worries! I appreciate the information you shared.
